#!/bin/bash

wget https://start.duckduckgo.com/assets/add-to-browser/bullet.svg
wget https://start.duckduckgo.com/assets/add-to-browser/ddg_stacked.png
wget https://start.duckduckgo.com/assets/add-to-browser/ddg_stacked@2x.png
wget https://start.duckduckgo.com/assets/add-to-browser/onboarding-v2@2x.jpg
wget https://start.duckduckgo.com/assets/dax.png
wget https://start.duckduckgo.com/assets/dax.retina.png
wget https://start.duckduckgo.com/assets/dax.svg
wget https://start.duckduckgo.com/assets/icons/browsers/small/arora.png
wget https://start.duckduckgo.com/assets/icons/browsers/small/arora.svg
wget https://start.duckduckgo.com/assets/icons/browsers/small/chrome.png
wget https://start.duckduckgo.com/assets/icons/browsers/small/chrome.svg
wget https://start.duckduckgo.com/assets/icons/browsers/small/ddg.png
wget https://start.duckduckgo.com/assets/icons/browsers/small/ddg.svg
wget https://start.duckduckgo.com/assets/icons/browsers/small/edge.png
wget https://start.duckduckgo.com/assets/icons/browsers/small/edge.svg
wget https://start.duckduckgo.com/assets/icons/browsers/small/firefox.png
wget https://start.duckduckgo.com/assets/icons/browsers/small/firefox.svg
wget https://start.duckduckgo.com/assets/icons/browsers/small/ie.png
wget https://start.duckduckgo.com/assets/icons/browsers/small/ie.svg
wget https://start.duckduckgo.com/assets/icons/browsers/small/maxthon.png
wget https://start.duckduckgo.com/assets/icons/browsers/small/maxthon.svg
wget https://start.duckduckgo.com/assets/icons/browsers/small/opera.png
wget https://start.duckduckgo.com/assets/icons/browsers/small/opera.svg
wget https://start.duckduckgo.com/assets/icons/browsers/small/palemoon.png
wget https://start.duckduckgo.com/assets/icons/browsers/small/palemoon.svg
wget https://start.duckduckgo.com/assets/icons/browsers/small/safari.png
wget https://start.duckduckgo.com/assets/icons/browsers/small/safari.svg
wget https://start.duckduckgo.com/assets/icons/browsers/small/seamonkey.png
wget https://start.duckduckgo.com/assets/icons/browsers/small/seamonkey.svg
wget https://start.duckduckgo.com/assets/icons/browsers/small/vivaldi.png
wget https://start.duckduckgo.com/assets/icons/browsers/small/vivaldi.svg
wget https://start.duckduckgo.com/assets/icons/meta/DDG-iOS-icon_120x120.png
wget https://start.duckduckgo.com/assets/icons/meta/DDG-iOS-icon_152x152.png
wget https://start.duckduckgo.com/assets/icons/meta/DDG-iOS-icon_60x60.png
wget https://start.duckduckgo.com/assets/icons/meta/DDG-iOS-icon_76x76.png
wget https://start.duckduckgo.com/assets/icons/meta/DDG-icon_256x256.png
wget https://start.duckduckgo.com/assets/logo_header.v107.lg.png
wget https://start.duckduckgo.com/assets/logo_header.v107.lg.retina.png
wget https://start.duckduckgo.com/assets/logo_header.v107.lg.svg
wget https://start.duckduckgo.com/assets/logo_header.v107.min.png
wget https://start.duckduckgo.com/assets/logo_header.v107.min.retina.png
wget https://start.duckduckgo.com/assets/logo_header.v107.min.svg
wget https://start.duckduckgo.com/assets/logo_header_alt.v103.lg.png
wget https://start.duckduckgo.com/assets/logo_header_alt.v103.lg.svg
wget https://start.duckduckgo.com/assets/logo_header_alt.v103.min.png
wget https://start.duckduckgo.com/assets/logo_header_alt.v103.min.retina.png
wget https://start.duckduckgo.com/assets/logo_header_alt.v103.min.svg
wget https://start.duckduckgo.com/assets/logo_header_alt.v107.lg.retina.png
wget https://start.duckduckgo.com/assets/logo_homepage.alt.v105.png
wget https://start.duckduckgo.com/assets/logo_homepage.alt.v105.retina.png
wget https://start.duckduckgo.com/assets/logo_homepage.alt.v106.svg
wget https://start.duckduckgo.com/assets/logo_homepage.normal.v107.png
wget https://start.duckduckgo.com/assets/logo_homepage.normal.v107.retina.png
wget https://start.duckduckgo.com/assets/logo_homepage.normal.v107.svg
wget https://start.duckduckgo.com/assets/logo_homepage_mobile.alt.v105.png
wget https://start.duckduckgo.com/assets/logo_homepage_mobile.alt.v105.retina.png
wget https://start.duckduckgo.com/assets/logo_homepage_mobile.alt.v106.svg
wget https://start.duckduckgo.com/assets/logo_homepage_mobile.normal.v107.png
wget https://start.duckduckgo.com/assets/logo_homepage_mobile.normal.v107.retina.png
wget https://start.duckduckgo.com/assets/logo_homepage_mobile.normal.v107.svg
wget https://start.duckduckgo.com/assets/logo_homepage_small.alt.v105.png
wget https://start.duckduckgo.com/assets/logo_homepage_small.alt.v105.retina.png
wget https://start.duckduckgo.com/assets/logo_homepage_small.alt.v107.svg
wget https://start.duckduckgo.com/assets/logo_homepage_small.normal.v107.png
wget https://start.duckduckgo.com/assets/logo_homepage_small.normal.v107.retina.png
wget https://start.duckduckgo.com/assets/logo_homepage_small.normal.v107.svg
wget https://start.duckduckgo.com/assets/logo_social-media.png
wget https://start.duckduckgo.com/assets/logos/initech/logo_homepage.png
wget https://start.duckduckgo.com/assets/logos/initech/logo_homepage.retina.png
wget https://start.duckduckgo.com/assets/logos/initech/logo_homepage.svg
wget https://start.duckduckgo.com/assets/logos/initech/logo_homepage_mobile.png
wget https://start.duckduckgo.com/assets/logos/initech/logo_homepage_mobile.retina.png
wget https://start.duckduckgo.com/assets/logos/initech/logo_homepage_mobile.svg
wget https://start.duckduckgo.com/assets/logos/initech/logo_homepage_small.retina.png
wget https://start.duckduckgo.com/assets/logos/resetthenet/logo_homepage.alt.png
wget https://start.duckduckgo.com/assets/logos/resetthenet/logo_homepage.alt.retina.png
wget https://start.duckduckgo.com/assets/logos/resetthenet/logo_homepage.alt.svg
wget https://start.duckduckgo.com/assets/logos/resetthenet/logo_homepage.normal.png
wget https://start.duckduckgo.com/assets/logos/resetthenet/logo_homepage.normal.retina.png
wget https://start.duckduckgo.com/assets/logos/resetthenet/logo_homepage.normal.svg
wget https://start.duckduckgo.com/assets/logos/resetthenet/logo_homepage_mobile.alt.png
wget https://start.duckduckgo.com/assets/logos/resetthenet/logo_homepage_mobile.alt.retina.png
wget https://start.duckduckgo.com/assets/logos/resetthenet/logo_homepage_mobile.alt.svg
wget https://start.duckduckgo.com/assets/logos/resetthenet/logo_homepage_mobile.normal.png
wget https://start.duckduckgo.com/assets/logos/resetthenet/logo_homepage_mobile.normal.retina.png
wget https://start.duckduckgo.com/assets/logos/resetthenet/logo_homepage_mobile.normal.svg
wget https://start.duckduckgo.com/assets/logos/resetthenet/logo_homepage_small.alt.png
wget https://start.duckduckgo.com/assets/logos/resetthenet/logo_homepage_small.alt.retina.png
wget https://start.duckduckgo.com/assets/logos/resetthenet/logo_homepage_small.alt.svg
wget https://start.duckduckgo.com/assets/logos/resetthenet/logo_homepage_small.normal.png
wget https://start.duckduckgo.com/assets/logos/resetthenet/logo_homepage_small.normal.retina.png
wget https://start.duckduckgo.com/assets/logos/resetthenet/logo_homepage_small.normal.svg
wget https://start.duckduckgo.com/assets/microsites/font/fontawesome-webfont.eot
wget https://start.duckduckgo.com/assets/microsites/font/fontawesome-webfont.svg
wget https://start.duckduckgo.com/assets/microsites/font/fontawesome-webfont.ttf
wget https://start.duckduckgo.com/assets/microsites/font/fontawesome-webfont.woff
wget https://start.duckduckgo.com/assets/onboarding/mobile/phone@2xl.png
wget https://start.duckduckgo.com/assets/onboarding/mobile/phone@2xm.png
wget https://start.duckduckgo.com/assets/onboarding/mobile/phone@2xs.png
wget https://start.duckduckgo.com/assets/settings/colorpicker-1d.100.png
wget https://start.duckduckgo.com/assets/settings/icon_cloudsave.v100.retina.png
wget https://start.duckduckgo.com/assets/spread/rocket-hero.v102.png
wget https://start.duckduckgo.com/assets/spread/rocket-hero.v102.svg
wget https://start.duckduckgo.com/assets/tour/down-arrow.png
wget https://start.duckduckgo.com/assets/tour/down-arrow.svg
